In [2]:
import numpy as n

In [3]:
ml = [1,2,3]
type(ml)

list

In [4]:
n.array(ml)

array([1, 2, 3])

In [5]:
ml

[1, 2, 3]

In [6]:
myarr = n.array(ml)
myarr

array([1, 2, 3])

In [7]:
type(myarr)

numpy.ndarray

In [8]:
my_matrix =[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
n.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
n.arange(10,100,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [16]:
n.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
n.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
n.linspace(0,10,5) #from 0 to 10 , 5 times 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [35]:
n.eye(10,10,2)

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
n.random.rand(10,10,2)

array([[[0.98679114, 0.90429132],
        [0.23957177, 0.2390281 ],
        [0.74016677, 0.5902819 ],
        [0.42028404, 0.3478952 ],
        [0.89152421, 0.37500971],
        [0.68213545, 0.264858  ],
        [0.19518354, 0.71793056],
        [0.23325858, 0.45236688],
        [0.15449702, 0.27755097],
        [0.30248688, 0.50903381]],

       [[0.86073986, 0.28890588],
        [0.28402139, 0.79521117],
        [0.6625422 , 0.32990612],
        [0.9854741 , 0.19452597],
        [0.52615861, 0.99046804],
        [0.71356204, 0.03044588],
        [0.54158344, 0.29314511],
        [0.71128129, 0.66147726],
        [0.12330265, 0.62072024],
        [0.55727833, 0.48785456]],

       [[0.25497036, 0.78161263],
        [0.77771864, 0.50656699],
        [0.72796751, 0.08703761],
        [0.7155285 , 0.6052037 ],
        [0.64908418, 0.6298829 ],
        [0.44229917, 0.57869727],
        [0.81188135, 0.30671625],
        [0.69198419, 0.18192512],
        [0.1222913 , 0.02355579],
        [0

In [49]:
n.random.randint(100)


17

In [50]:
n.random.randint(0,101,(3,3))

array([[36, 95, 41],
       [96, 31, 57],
       [81, 20, 85]])

In [52]:
n.random.seed(20)
n.random.rand(6)


array([0.67286566, 0.04117333, 0.84157413, 0.8165543 , 0.78251141,
       0.73526734])

In [62]:
arr = n.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [63]:
arr.reshape(10,10)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])